// Generated by CoffeeScript 1.3.3

describe("Hoodie.Share", function() {
  beforeEach(function() {
    this.hoodie = new Mocks.Hoodie;
    return this.share = new Hoodie.Share(this.hoodie);
  });
  return describe(".constructor", function() {
    return it("should set Hoodie.Share.Instance.hoodie", function() {
      var hoodie;
      hoodie = 'check 1,2';
      new Hoodie.Share(hoodie);
      return expect(Hoodie.Share.Instance.hoodie).toBe('check 1,2');
    });
  });
});
