// Generated by CoffeeScript 1.3.3

define('specs/hoodie/sharing', ['mocks/hoodie', 'hoodie/sharing', 'hoodie/sharing/instance'], function(HoodieMock, Sharing, SharingInstance) {
  return describe("Sharing", function() {
    beforeEach(function() {
      this.hoodie = new HoodieMock;
      return this.sharing = new Sharing(this.hoodie);
    });
    return describe(".constructor", function() {
      return it("should set SharingInstance.hoodie", function() {
        var hoodie;
        hoodie = 'check 1,2';
        new Sharing(hoodie);
        return expect(SharingInstance.hoodie).toBe('check 1,2');
      });
    });
  });
});
