// Generated by CoffeeScript 1.3.3

describe("Hoodie.User", function() {
  return beforeEach(function() {
    this.hoodie = new Mocks.Hoodie;
    return this.user = new Hoodie.User(this.hoodie);
  });
});
