// Generated by CoffeeScript 1.3.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Hoodie.Sharing.Account = (function(_super) {

  __extends(Account, _super);

  function Account() {
    Account.__super__.constructor.apply(this, arguments);
    this._sharingAuthPromise = this.hoodie.defer().resolve(this.username).promise();
  }

  Account.prototype.authenticate = function() {
    return this._sharingAuthPromise;
  };

  Account.prototype.signUp = function() {
    return this._sharingAuthPromise;
  };

  Account.prototype.signIn = function() {
    return this._sharingAuthPromise;
  };

  Account.prototype.signOut = function() {
    return this._sharingAuthPromise;
  };

  return Account;

})(Hoodie.Account);
