// Generated by CoffeeScript 1.3.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

define('hoodie/sharing/hoodie', ['hoodie'], function(Hoodie) {
  var SharingHoodie;
  return SharingHoodie = (function(_super) {

    __extends(SharingHoodie, _super);

    SharingHoodie.name = 'SharingHoodie';

    SharingHoodie.prototype.modules = ['hoodie/account', 'hoodie/remote'];

    function SharingHoodie(hoodie, sharing) {
      this.store = hoodie.store;
      this.config = sharing.config;
      SharingHoodie.__super__.constructor.call(this, hoodie.base_url);
    }

    return SharingHoodie;

  })(Hoodie);
});
