// Generated by CoffeeScript 1.3.3
var Events,
  __slice = [].slice;

Events = (function() {

  function Events() {}

  Events.prototype.bind = function(ev, callback) {
    var calls, evs, name, _i, _len, _results;
    evs = ev.split(' ');
    calls = this.hasOwnProperty('_callbacks') && this._callbacks || (this._callbacks = {});
    _results = [];
    for (_i = 0, _len = evs.length; _i < _len; _i++) {
      name = evs[_i];
      calls[name] || (calls[name] = []);
      _results.push(calls[name].push(callback));
    }
    return _results;
  };

  Events.prototype.on = Events.prototype.bind;

  Events.prototype.one = function(ev, callback) {
    return this.bind(ev, function() {
      this.unbind(ev, arguments.callee);
      return callback.apply(this, arguments);
    });
  };

  Events.prototype.trigger = function() {
    var args, callback, ev, list, _i, _len, _ref;
    args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    ev = args.shift();
    list = this.hasOwnProperty('_callbacks') && ((_ref = this._callbacks) != null ? _ref[ev] : void 0);
    if (!list) {
      return;
    }
    for (_i = 0, _len = list.length; _i < _len; _i++) {
      callback = list[_i];
      callback.apply(this, args);
    }
    return true;
  };

  Events.prototype.unbind = function(ev, callback) {
    var cb, i, list, _i, _len, _ref;
    if (!ev) {
      this._callbacks = {};
      return this;
    }
    list = (_ref = this._callbacks) != null ? _ref[ev] : void 0;
    if (!list) {
      return this;
    }
    if (!callback) {
      delete this._callbacks[ev];
      return this;
    }
    for (i = _i = 0, _len = list.length; _i < _len; i = ++_i) {
      cb = list[i];
      if (!(cb === callback)) {
        continue;
      }
      list = list.slice();
      list.splice(i, 1);
      this._callbacks[ev] = list;
      break;
    }
    return this;
  };

  return Events;

})();
// Generated by CoffeeScript 1.3.3
var Hoodie,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Hoodie = (function(_super) {

  __extends(Hoodie, _super);

  Hoodie.prototype.modules = function() {
    return {
      my: {
        store: Hoodie.LocalStore,
        config: Hoodie.Config,
        account: Hoodie.Account,
        remote: Hoodie.Account.RemoteStore
      },
      user: Hoodie.User,
      global: Hoodie.Global,
      email: Hoodie.Email,
      share: Hoodie.Share
    };
  };

  function Hoodie(baseUrl) {
    this.baseUrl = baseUrl != null ? baseUrl : '';
    this.baseUrl = this.baseUrl.replace(/\/+$/, '');
    this._loadModules();
  }

  Hoodie.prototype.request = function(type, path, options) {
    var defaults;
    if (options == null) {
      options = {};
    }
    defaults = {
      type: type,
      url: "" + this.baseUrl + path,
      xhrFields: {
        withCredentials: true
      },
      crossDomain: true,
      dataType: 'json'
    };
    return $.ajax($.extend(defaults, options));
  };

  Hoodie.prototype.open = function(store_name, options) {
    if (options == null) {
      options = {};
    }
    $.extend(options, {
      basePath: "/" + (encodeURIComponent(store_name))
    });
    return new Hoodie.RemoteStore(this, options);
  };

  Hoodie.prototype.defer = $.Deferred;

  Hoodie.prototype.isPromise = function(obj) {
    return typeof (obj != null ? obj.done : void 0) === 'function' && typeof obj.resolve === 'undefined';
  };

  Hoodie.prototype._loadModules = function(context, modules) {
    var Module, instanceName, namespace, _results;
    if (context == null) {
      context = this;
    }
    if (modules == null) {
      modules = this.modules();
    }
    _results = [];
    for (instanceName in modules) {
      Module = modules[instanceName];
      if (typeof Module === 'function') {
        _results.push(context[instanceName] = new Module(this));
      } else {
        namespace = instanceName;
        context[namespace] || (context[namespace] = {});
        _results.push(this._loadModules(context[namespace], modules[namespace]));
      }
    }
    return _results;
  };

  return Hoodie;

})(Events);
// Generated by CoffeeScript 1.3.3
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

Hoodie.Account = (function() {

  Account.prototype.username = void 0;

  function Account(hoodie) {
    this.hoodie = hoodie;
    this._handleDestroySucces = __bind(this._handleDestroySucces, this);

    this._handleFetchBeforeDestroySucces = __bind(this._handleFetchBeforeDestroySucces, this);

    this._handlePasswordResetStatusRequestError = __bind(this._handlePasswordResetStatusRequestError, this);

    this._handlePasswordResetStatusRequestSuccess = __bind(this._handlePasswordResetStatusRequestSuccess, this);

    this._checkPasswordResetStatus = __bind(this._checkPasswordResetStatus, this);

    this._handleSignOutSuccess = __bind(this._handleSignOutSuccess, this);

    this._handleSignInSuccess = __bind(this._handleSignInSuccess, this);

    this._delayedSignIn = __bind(this._delayedSignIn, this);

    this._handleSignUpSucces = __bind(this._handleSignUpSucces, this);

    this._handleRequestError = __bind(this._handleRequestError, this);

    this._handleAuthenticateSuccess = __bind(this._handleAuthenticateSuccess, this);

    this.fetch = __bind(this.fetch, this);

    this.authenticate = __bind(this.authenticate, this);

    this.username = this.hoodie.my.config.get('_account.username');
    this.owner = this.hoodie.my.config.get('_account.owner');
    if (!this.owner) {
      this.owner = this.hoodie.my.store.uuid();
      this.hoodie.my.config.set('_account.owner', this.owner);
    }
    this._checkPasswordResetStatus();
  }

  Account.prototype.authenticate = function() {
    if (!this.username) {
      return this.hoodie.defer().reject().promise();
    }
    if (this._authenticated === true) {
      return this.hoodie.defer().resolve(this.username).promise();
    }
    if (this._authenticated === false) {
      return this.hoodie.defer().reject().promise();
    }
    return this.hoodie.request('GET', "/_session").pipe(this._handleAuthenticateSuccess, this._handleRequestError);
  };

  Account.prototype.signUp = function(username, password) {
    var options;
    if (password == null) {
      password = '';
    }
    if (this.hasAnonymousAccount()) {
      return this._upgradeAnonymousAccount(username, password);
    }
    options = {
      data: JSON.stringify({
        _id: this._key(username),
        name: this._userKey(username),
        type: 'user',
        roles: [],
        password: password,
        $owner: this.owner,
        database: this.db()
      }),
      contentType: 'application/json'
    };
    return this.hoodie.request('PUT', this._url(username), options).pipe(this._handleSignUpSucces(username, password), this._handleRequestError);
  };

  Account.prototype.anonymousSignUp = function() {
    var password, username,
      _this = this;
    password = this.hoodie.my.store.uuid(10);
    username = this.owner;
    return this.signUp(username, password).fail(this._handleRequestError).done(function() {
      return _this.hoodie.my.config.set('_account.anonymousPassword', password);
    });
  };

  Account.prototype.hasAnonymousAccount = function() {
    return this.hoodie.my.config.get('_account.anonymousPassword') != null;
  };

  Account.prototype.signIn = function(username, password) {
    var options;
    if (password == null) {
      password = '';
    }
    options = {
      data: {
        name: this._userKey(username),
        password: password
      }
    };
    return this.hoodie.request('POST', '/_session', options).pipe(this._handleSignInSuccess);
  };

  Account.prototype.login = Account.prototype.signIn;

  Account.prototype.signOut = function() {
    this.hoodie.my.remote.disconnect();
    return this.hoodie.request('DELETE', '/_session').pipe(this._handleSignOutSuccess);
  };

  Account.prototype.logout = Account.prototype.signOut;

  Account.prototype.on = function(event, cb) {
    return this.hoodie.on("account:" + event, cb);
  };

  Account.prototype.db = function() {
    return "user/" + this.owner;
  };

  Account.prototype.fetch = function(username) {
    if (username == null) {
      username = this.username;
    }
    if (!username) {
      return this.hoodie.defer().reject({
        error: "unauthenticated",
        reason: "not logged in"
      }).promise();
    }
    return this.hoodie.request('GET', this._url(username)).pipe(null, this._handleRequestError).done(function(response) {
      return response = this._doc;
    });
  };

  Account.prototype.changePassword = function(currentPassword, newPassword) {
    var data, options;
    if (!this.username) {
      return this.hoodie.defer().reject({
        error: "unauthenticated",
        reason: "not logged in"
      }).promise();
    }
    data = $.extend({}, this._doc);
    data.password = newPassword;
    delete data.salt;
    delete data.password_sha;
    options = {
      data: JSON.stringify(data),
      contentType: "application/json"
    };
    this.hoodie.my.remote.disconnect();
    return this.hoodie.request('PUT', this._url(), options).pipe(this._handleChangePasswordSuccess(newPassword), this._handleRequestError);
  };

  Account.prototype.resetPassword = function(username) {
    var data, key, options, resetPasswordId;
    if (resetPasswordId = this.hoodie.my.config.get('_account.resetPasswordId')) {
      return this._checkPasswordResetStatus();
    }
    resetPasswordId = "" + username + "/" + (this.hoodie.my.store.uuid());
    this.hoodie.my.config.set('_account.resetPasswordId', resetPasswordId);
    key = "" + this._prefix + ":$passwordReset/" + resetPasswordId;
    data = {
      _id: key,
      name: "$passwordReset/" + resetPasswordId,
      type: 'user',
      password: resetPasswordId,
      createdAt: new Date,
      updatedAt: new Date
    };
    options = {
      data: JSON.stringify(data),
      contentType: "application/json"
    };
    return this.hoodie.request('PUT', "/_users/" + (encodeURIComponent(key)), options).pipe(null, this._handleRequestError).done(this._checkPasswordResetStatus);
  };

  Account.prototype.changeUsername = function(currentPassword, newUsername) {
    return this._changeUsernameAndPassword(currentPassword, newUsername);
  };

  Account.prototype.destroy = function() {
    return this.fetch().pipe(this._handleFetchBeforeDestroySucces, this._handleRequestError).pipe(this._handleDestroySucces);
  };

  Account.prototype._prefix = 'org.couchdb.user';

  Account.prototype._doc = {};

  Account.prototype._setUsername = function(username) {
    this.username = username;
    return this.hoodie.my.config.set('_account.username', this.username);
  };

  Account.prototype._setOwner = function(owner) {
    this.owner = owner;
    return this.hoodie.my.config.set('_account.owner', this.owner);
  };

  Account.prototype._handleAuthenticateSuccess = function(response) {
    var defer;
    defer = this.hoodie.defer();
    if (response.userCtx.name) {
      this._authenticated = true;
      this._setUsername(response.userCtx.name.replace(/^user(_anonymous)?\//, ''));
      this._setOwner(response.userCtx.roles[0]);
      defer.resolve(this.username);
    } else {
      this._authenticated = false;
      this.hoodie.trigger('account:error:unauthenticated');
      defer.reject();
    }
    return defer.promise();
  };

  Account.prototype._handleRequestError = function(xhr) {
    var error;
    if (xhr == null) {
      xhr = {};
    }
    try {
      error = JSON.parse(xhr.responseText);
    } catch (e) {
      error = {
        error: xhr.responseText || "unknown"
      };
    }
    return this.hoodie.defer().reject(error).promise();
  };

  Account.prototype._handleSignUpSucces = function(username, password) {
    var defer,
      _this = this;
    defer = this.hoodie.defer();
    return function(response) {
      _this.hoodie.trigger('account:signup', username);
      _this._doc._rev = response.rev;
      return _this._delayedSignIn(username, password);
    };
  };

  Account.prototype._delayedSignIn = function(username, password) {
    var defer,
      _this = this;
    defer = this.hoodie.defer();
    window.setTimeout((function() {
      var promise;
      promise = _this.signIn(username, password);
      promise.done(defer.resolve);
      return promise.fail(function(error) {
        if (error.error === 'unconfirmed') {
          return _this._delayedSignIn(username, password);
        } else {
          return defer.reject.apply(defer, arguments);
        }
      });
    }), 300);
    return defer.promise();
  };

  Account.prototype._handleSignInSuccess = function(response) {
    var defer, username,
      _this = this;
    defer = this.hoodie.defer();
    username = response.name.replace(/^user(_anonymous)?\//, '');
    if (~response.roles.indexOf("error")) {
      this.fetch(username).fail(defer.reject).done(function() {
        return defer.reject({
          error: "error",
          reason: _this._doc.$error
        });
      });
      return defer.promise();
    }
    if (!~response.roles.indexOf("confirmed")) {
      return defer.reject({
        error: "unconfirmed",
        reason: "account has not been confirmed yet"
      });
    }
    this._authenticated = true;
    this._setUsername(username);
    this._setOwner(response.roles[0]);
    this.hoodie.trigger('account:signin', this.username);
    this.fetch();
    return defer.resolve(this.username, response);
  };

  Account.prototype._handleChangePasswordSuccess = function(newPassword) {
    var _this = this;
    return function() {
      return _this.signIn(_this.username, newPassword);
    };
  };

  Account.prototype._handleSignOutSuccess = function() {
    delete this.username;
    delete this.owner;
    this.hoodie.my.config.clear();
    this._authenticated = false;
    return this.hoodie.trigger('account:signout');
  };

  Account.prototype._checkPasswordResetStatus = function() {
    var hash, options, resetPasswordId, url, username,
      _this = this;
    resetPasswordId = this.hoodie.my.config.get('_account.resetPasswordId');
    if (!resetPasswordId) {
      return this.hoodie.defer().reject({
        error: "missing"
      }).promise();
    }
    username = "$passwordReset/" + resetPasswordId;
    url = "/_users/" + (encodeURIComponent("" + this._prefix + ":" + username));
    hash = btoa("" + username + ":" + resetPasswordId);
    options = {
      headers: {
        Authorization: "Basic " + hash
      }
    };
    return this.hoodie.request('GET', url, options).pipe(this._handlePasswordResetStatusRequestSuccess, this._handlePasswordResetStatusRequestError).fail(function() {
      if (error.error === 'pending') {
        window.setTimeout(_this._checkPasswordResetStatus, 1000);
        return;
      }
      return _this.hoodie.trigger('account:password_reset:error');
    });
  };

  Account.prototype._handlePasswordResetStatusRequestSuccess = function() {
    var defer;
    defer = this.hoodie.defer();
    if (response.$error) {
      defer.reject({
        error: response.$error
      });
    } else {
      defer.reject({
        error: 'pending'
      });
    }
    return defer.promise();
  };

  Account.prototype._handlePasswordResetStatusRequestError = function(xhr) {
    if (xhr.status === 401) {
      this.hoodie.defer().resolve();
      this.hoodie.my.config.remove('_account.resetPasswordId');
      return this.hoodie.trigger('account:password_reset:success');
    } else {
      return this._handleRequestError(xhr);
    }
  };

  Account.prototype._changeUsernameAndPassword = function(currentPassword, newUsername, newPassword) {
    var _this = this;
    return this.authenticate().pipe(function() {
      var data, options;
      data = $.extend({}, _this._doc);
      data.$newUsername = newUsername;
      if (newPassword) {
        delete data.salt;
        delete data.password_sha;
        data.password = newPassword;
      }
      options = {
        data: JSON.stringify(data),
        contentType: 'application/json'
      };
      return _this.hoodie.request('PUT', _this._url(), options).pipe(function() {
        _this.hoodie.my.remote.disconnect();
        return _this._delayedSignIn(newUsername, newPassword || currentPassword);
      });
    });
  };

  Account.prototype._upgradeAnonymousAccount = function(username, password) {
    var currentPassword,
      _this = this;
    currentPassword = this.hoodie.my.config.get('_account.anonymousPassword');
    return this._changeUsernameAndPassword(currentPassword, username, password).done(function() {
      return _this.hoodie.my.config.remove('_account.anonymousPassword');
    });
  };

  Account.prototype._handleFetchBeforeDestroySucces = function() {
    this.hoodie.my.remote.disconnect();
    this._doc._deleted = true;
    return this.hoodie.request('PUT', this._url(), {
      data: JSON.stringify(this._doc),
      contentType: 'application/json'
    });
  };

  Account.prototype._handleDestroySucces = function() {
    delete this.username;
    delete this.owner;
    return delete this._authenticated;
  };

  Account.prototype._userKey = function(username) {
    if (username === this.owner) {
      return "user_anonymous/" + username;
    } else {
      return "user/" + username;
    }
  };

  Account.prototype._key = function(username) {
    if (username == null) {
      username = this.username;
    }
    return "" + this._prefix + ":" + (this._userKey(username));
  };

  Account.prototype._url = function(username) {
    if (username == null) {
      username = this.username;
    }
    return "/_users/" + (encodeURIComponent(this._key(username)));
  };

  return Account;

})();
// Generated by CoffeeScript 1.3.3

Hoodie.Store = (function() {

  function Store(hoodie) {
    this.hoodie = hoodie;
  }

  Store.prototype.save = function(type, id, object, options) {
    var defer;
    if (options == null) {
      options = {};
    }
    defer = this.hoodie.defer();
    if (typeof object !== 'object') {
      defer.reject(Hoodie.Errors.INVALID_ARGUMENTS("object is " + (typeof object)));
      return defer.promise();
    }
    if (id && !this._isValidId(id)) {
      return defer.reject(Hoodie.Errors.INVALID_KEY({
        id: id
      })).promise();
    }
    if (!this._isValidType(type)) {
      return defer.reject(Hoodie.Errors.INVALID_KEY({
        type: type
      })).promise();
    }
    return defer;
  };

  Store.prototype.create = function(type, object, options) {
    if (object == null) {
      object = {};
    }
    if (options == null) {
      options = {};
    }
    return this.save(type, object.id, object);
  };

  Store.prototype.update = function(type, id, objectUpdate, options) {
    var defer, _loadPromise,
      _this = this;
    if (options == null) {
      options = {};
    }
    defer = this.hoodie.defer();
    _loadPromise = this.find(type, id).pipe(function(currentObj) {
      var changedProperties, key, value;
      if (typeof objectUpdate === 'function') {
        objectUpdate = objectUpdate($.extend({}, currentObj));
      }
      if (!objectUpdate) {
        return defer.resolve(currentObj);
      }
      changedProperties = (function() {
        var _results;
        _results = [];
        for (key in objectUpdate) {
          value = objectUpdate[key];
          if (!(currentObj[key] !== value)) {
            continue;
          }
          currentObj[key] = value;
          _results.push(key);
        }
        return _results;
      })();
      if (!changedProperties.length) {
        return defer.resolve(currentObj);
      }
      return _this.save(type, id, currentObj, options).then(defer.resolve, defer.reject);
    });
    _loadPromise.fail(function() {
      return _this.save(type, id, objectUpdate, options).then(defer.resolve, defer.reject);
    });
    return defer.promise();
  };

  Store.prototype.updateAll = function(filterOrObjects, objectUpdate, options) {
    var promise,
      _this = this;
    if (options == null) {
      options = {};
    }
    switch (true) {
      case typeof filterOrObjects === 'string':
        promise = this.findAll(filterOrObjects);
        break;
      case this.hoodie.isPromise(filterOrObjects):
        promise = filterOrObjects;
        break;
      case $.isArray(filterOrObjects):
        promise = this.hoodie.defer().resolve(filterOrObjects).resolve();
        break;
      default:
        promise = this.findAll();
    }
    return promise.pipe(function(objects) {
      var defer, object, _updatePromises;
      defer = _this.hoodie.defer();
      _updatePromises = (function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = objects.length; _i < _len; _i++) {
          object = objects[_i];
          _results.push(this.update(object.type, object.id, objectUpdate, options));
        }
        return _results;
      }).call(_this);
      $.when.apply(null, _updatePromises).then(defer.resolve);
      return defer.promise();
    });
  };

  Store.prototype.find = function(type, id) {
    var defer;
    defer = this.hoodie.defer();
    if (!(typeof type === 'string' && typeof id === 'string')) {
      return defer.reject(Hoodie.Errors.INVALID_ARGUMENTS("type & id are required")).promise();
    }
    return defer;
  };

  Store.prototype.findOrCreate = function(type, id, attributes) {
    var defer,
      _this = this;
    if (attributes == null) {
      attributes = {};
    }
    defer = this.hoodie.defer();
    this.find(type, id).done(defer.resolve).fail(function() {
      var newAttributes;
      newAttributes = $.extend({
        id: id
      }, attributes);
      return _this.create(type, newAttributes).then(defer.resolve, defer.reject);
    });
    return defer.promise();
  };

  Store.prototype.findAll = function() {
    return this.hoodie.defer();
  };

  Store.prototype.loadAll = function() {
    return this.findAll.apply(this, arguments);
  };

  Store.prototype.destroy = function(type, id, options) {
    var defer;
    if (options == null) {
      options = {};
    }
    defer = this.hoodie.defer();
    if (!(typeof type === 'string' && typeof id === 'string')) {
      return defer.reject(Hoodie.Errors.INVALID_ARGUMENTS("type & id are required")).promise();
    }
    return defer;
  };

  Store.prototype["delete"] = function() {
    return this.destroy.apply(this, arguments);
  };

  Store.prototype.destroyAll = function(type, options) {
    var _this = this;
    if (options == null) {
      options = {};
    }
    return this.findAll(type).pipe(function(objects) {
      var object, _i, _len, _results;
      _results = [];
      for (_i = 0, _len = objects.length; _i < _len; _i++) {
        object = objects[_i];
        _results.push(_this.destroy(object.type, object.id, options));
      }
      return _results;
    });
  };

  Store.prototype.uuid = function(len) {
    var chars, i, radix;
    if (len == null) {
      len = 7;
    }
    chars = '0123456789abcdefghijklmnopqrstuvwxyz'.split('');
    radix = chars.length;
    return ((function() {
      var _i, _results;
      _results = [];
      for (i = _i = 0; 0 <= len ? _i < len : _i > len; i = 0 <= len ? ++_i : --_i) {
        _results.push(chars[0 | Math.random() * radix]);
      }
      return _results;
    })()).join('');
  };

  Store.prototype._now = function() {
    return new Date;
  };

  Store.prototype._isValidId = function(key) {
    return /^[a-z0-9\-]+$/.test(key);
  };

  Store.prototype._isValidType = function(key) {
    return /^[a-z$][a-z0-9]+$/.test(key);
  };

  return Store;

})();
// Generated by CoffeeScript 1.3.3
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  __slice = [].slice;

Hoodie.RemoteStore = (function(_super) {

  __extends(RemoteStore, _super);

  RemoteStore.prototype._sync = false;

  function RemoteStore(hoodie, options) {
    this.hoodie = hoodie;
    if (options == null) {
      options = {};
    }
    this._handlePushSuccess = __bind(this._handlePushSuccess, this);

    this._handlePullResults = __bind(this._handlePullResults, this);

    this._handlePullError = __bind(this._handlePullError, this);

    this._handlePullSuccess = __bind(this._handlePullSuccess, this);

    this._restartPullRequest = __bind(this._restartPullRequest, this);

    this.sync = __bind(this.sync, this);

    this.push = __bind(this.push, this);

    this.pull = __bind(this.pull, this);

    this.disconnect = __bind(this.disconnect, this);

    this.connect = __bind(this.connect, this);

    this.basePath = options.basePath || '';
    if (options.sync) {
      this._sync = options.sync;
    }
  }

  RemoteStore.prototype.find = function(type, id) {
    var defer, path;
    defer = RemoteStore.__super__.find.apply(this, arguments);
    if (this.hoodie.isPromise(defer)) {
      return defer;
    }
    path = "/" + encodeURIComponent("" + type + "/" + id);
    return this.request("GET", path);
  };

  RemoteStore.prototype.findAll = function(type) {
    var defer, path, promise;
    defer = RemoteStore.__super__.findAll.apply(this, arguments);
    if (this.hoodie.isPromise(defer)) {
      return defer;
    }
    path = "/_all_docs";
    if (type) {
      path = "" + path + "?startkey=\"" + type + "\"&endkey=\"" + type + "0\"";
    }
    promise = this.request("GET", path);
    promise.fail(defer.reject);
    promise.done(function(response) {
      return defer.resolve(response.rows);
    });
    return defer.promise();
  };

  RemoteStore.prototype.save = function(type, id, object) {
    var defer, doc, path;
    defer = RemoteStore.__super__.save.apply(this, arguments);
    if (this.hoodie.isPromise(defer)) {
      return defer;
    }
    if (!id) {
      id = this.uuid();
    }
    object = $.extend({
      type: type,
      id: id
    }, object);
    doc = this._parseForRemote(object);
    path = "/" + encodeURIComponent(doc._id);
    return this.request("PUT", path, {
      data: doc
    });
  };

  RemoteStore.prototype.destroy = function(type, id) {
    return this.update(type, id, {
      _deleted: true
    });
  };

  RemoteStore.prototype.destroyAll = function(type) {
    return this.updateAll(type, {
      _deleted: true
    });
  };

  RemoteStore.prototype.request = function(type, path, options) {
    if (options == null) {
      options = {};
    }
    path = this.basePath + path;
    options.contentType || (options.contentType = 'application/json');
    if (type === 'POST' || type === 'PUT') {
      options.dataType || (options.dataType = 'json');
      options.processData || (options.processData = false);
      options.data = JSON.stringify(options.data);
    }
    return this.hoodie.request(type, path, options);
  };

  RemoteStore.prototype.get = function(view_name, params) {
    return console.log.apply(console, [".get() not yet implemented"].concat(__slice.call(arguments)));
  };

  RemoteStore.prototype.post = function(update_function_name, params) {
    return console.log.apply(console, [".post() not yet implemented"].concat(__slice.call(arguments)));
  };

  RemoteStore.prototype.connect = function() {
    this.connected = true;
    return this.sync();
  };

  RemoteStore.prototype.disconnect = function() {
    var _ref, _ref1;
    this.connected = false;
    this.hoodie.unbind('store:dirty:idle', this.push);
    if ((_ref = this._pullRequest) != null) {
      _ref.abort();
    }
    return (_ref1 = this._pushRequest) != null ? _ref1.abort() : void 0;
  };

  RemoteStore.prototype.isContinuouslyPulling = function() {
    var _ref;
    return this._sync === true || ((_ref = this._sync) != null ? _ref.pull : void 0) === true;
  };

  RemoteStore.prototype.isContinuouslyPushing = function() {
    var _ref;
    return this._sync === true || ((_ref = this._sync) != null ? _ref.push : void 0) === true;
  };

  RemoteStore.prototype.isContinuouslySyncing = function() {
    return this._sync === true;
  };

  RemoteStore.prototype.getSinceNr = function() {
    return this._since || 0;
  };

  RemoteStore.prototype.setSinceNr = function(seq) {
    return this._since = seq;
  };

  RemoteStore.prototype.pull = function() {
    this._pullRequest = this.request('GET', this._pullUrl());
    if (this.connected && this.isContinuouslyPulling()) {
      window.clearTimeout(this._pullRequestTimeout);
      this._pullRequestTimeout = window.setTimeout(this._restartPullRequest, 25000);
    }
    return this._pullRequest.then(this._handlePullSuccess, this._handlePullError);
  };

  RemoteStore.prototype.push = function(docs) {
    var doc, docsForRemote;
    if (!(docs != null ? docs.length : void 0)) {
      return this.hoodie.defer().resolve([]).promise();
    }
    docsForRemote = (function() {
      var _i, _len, _results;
      _results = [];
      for (_i = 0, _len = docs.length; _i < _len; _i++) {
        doc = docs[_i];
        this._addRevisionTo(doc);
        _results.push(this._parseForRemote(doc));
      }
      return _results;
    }).call(this);
    this._pushRequest = this.request('POST', "/_bulk_docs", {
      data: {
        docs: docsForRemote,
        new_edits: false
      }
    });
    return this._pushRequest.done(this._handlePushSuccess(docs, docsForRemote));
  };

  RemoteStore.prototype.sync = function(docs) {
    if (this.isContinuouslyPushing()) {
      this.hoodie.unbind('store:dirty:idle', this.push);
      this.hoodie.on('store:dirty:idle', this.push);
    }
    return this.push(docs).pipe(this.pull);
  };

  RemoteStore.prototype.on = function(event, cb) {
    return this.hoodie.on("remote:" + event, cb);
  };

  RemoteStore.prototype._pullUrl = function() {
    var since;
    since = this.getSinceNr();
    if (this.isContinuouslyPulling()) {
      return "/_changes?include_docs=true&since=" + since + "&heartbeat=10000&feed=longpoll";
    } else {
      return "/_changes?include_docs=true&since=" + since;
    }
  };

  RemoteStore.prototype._restartPullRequest = function() {
    var _ref;
    return (_ref = this._pullRequest) != null ? _ref.abort() : void 0;
  };

  RemoteStore.prototype._handlePullSuccess = function(response) {
    this.setSinceNr(response.last_seq);
    this._handlePullResults(response.results);
    if (this.connected && this.isContinuouslyPulling()) {
      return this.pull();
    }
  };

  RemoteStore.prototype._handlePullError = function(xhr, error, resp) {
    if (!this.connected) {
      return;
    }
    switch (xhr.status) {
      case 403:
        this.hoodie.trigger('remote:error:unauthenticated', error);
        return this.disconnect();
      case 404:
        return window.setTimeout(this.pull, 3000);
      case 500:
        this.hoodie.trigger('remote:error:server', error);
        return window.setTimeout(this.pull, 3000);
      default:
        if (!this.isContinuouslyPulling()) {
          return;
        }
        if (xhr.statusText === 'abort') {
          return this.pull();
        } else {
          return window.setTimeout(this.pull, 3000);
        }
    }
  };

  RemoteStore.prototype._validSpecialAttributes = ['_id', '_rev', '_deleted', '_revisions', '_attachments'];

  RemoteStore.prototype._parseForRemote = function(obj) {
    var attr, attributes;
    attributes = $.extend({}, obj);
    for (attr in attributes) {
      if (~this._validSpecialAttributes.indexOf(attr)) {
        continue;
      }
      if (!/^_/.test(attr)) {
        continue;
      }
      delete attributes[attr];
    }
    attributes._id = "" + attributes.type + "/" + attributes.id;
    delete attributes.id;
    return attributes;
  };

  RemoteStore.prototype._generateNewRevisionId = function() {
    var timestamp, uuid;
    this._timezoneOffset || (this._timezoneOffset = new Date().getTimezoneOffset() * 60);
    timestamp = Date.now() + this._timezoneOffset;
    uuid = this.hoodie.my.store.uuid(5);
    return "" + uuid + "#" + timestamp;
  };

  RemoteStore.prototype._addRevisionTo = function(attributes) {
    var currentRevId, currentRevNr, newRevisionId, _ref;
    try {
      _ref = attributes._rev.split(/-/), currentRevNr = _ref[0], currentRevId = _ref[1];
    } catch (_error) {}
    currentRevNr = parseInt(currentRevNr, 10) || 0;
    newRevisionId = this._generateNewRevisionId();
    attributes._rev = "" + (currentRevNr + 1) + "-" + newRevisionId;
    attributes._revisions = {
      start: 1,
      ids: [newRevisionId]
    };
    if (currentRevId) {
      attributes._revisions.start += currentRevNr;
      return attributes._revisions.ids.push(currentRevId);
    }
  };

  RemoteStore.prototype._parseFromPull = function(obj) {
    var id, _ref;
    id = obj._id || obj.id;
    delete obj._id;
    _ref = id.split(/\//), obj.type = _ref[0], obj.id = _ref[1];
    if (obj.createdAt) {
      obj.createdAt = new Date(Date.parse(obj.createdAt));
    }
    if (obj.updatedAt) {
      obj.updatedAt = new Date(Date.parse(obj.updatedAt));
    }
    if (obj.rev) {
      obj._rev = obj.rev;
      delete obj.rev;
    }
    return obj;
  };

  RemoteStore.prototype._parseFromPush = function(obj) {
    var id, _ref;
    id = obj._id || delete obj._id;
    _ref = obj.id.split(/\//), obj.type = _ref[0], obj.id = _ref[1];
    obj._rev = obj.rev;
    delete obj.rev;
    delete obj.ok;
    return obj;
  };

  RemoteStore.prototype._handlePullResults = function(changes) {
    var doc, promise, _changedDocs, _destroyedDocs, _i, _j, _k, _len, _len1, _len2, _ref, _ref1, _results,
      _this = this;
    _destroyedDocs = [];
    _changedDocs = [];
    for (_i = 0, _len = changes.length; _i < _len; _i++) {
      doc = changes[_i].doc;
      doc = this._parseFromPull(doc);
      if (doc._deleted) {
        _destroyedDocs.push([
          doc, this.hoodie.my.store.destroy(doc.type, doc.id, {
            remote: true
          })
        ]);
      } else {
        _changedDocs.push([
          doc, this.hoodie.my.store.update(doc.type, doc.id, doc, {
            remote: true
          })
        ]);
      }
    }
    for (_j = 0, _len1 = _destroyedDocs.length; _j < _len1; _j++) {
      _ref = _destroyedDocs[_j], doc = _ref[0], promise = _ref[1];
      promise.then(function(object) {
        _this.hoodie.trigger('remote:destroy', object);
        _this.hoodie.trigger("remote:destroy:" + doc.type, object);
        _this.hoodie.trigger("remote:destroy:" + doc.type + ":" + doc.id, object);
        _this.hoodie.trigger('remote:change', 'destroy', object);
        _this.hoodie.trigger("remote:change:" + doc.type, 'destroy', object);
        return _this.hoodie.trigger("remote:change:" + doc.type + ":" + doc.id, 'destroy', object);
      });
    }
    _results = [];
    for (_k = 0, _len2 = _changedDocs.length; _k < _len2; _k++) {
      _ref1 = _changedDocs[_k], doc = _ref1[0], promise = _ref1[1];
      _results.push(promise.then(function(object, objectWasCreated) {
        var event;
        event = objectWasCreated ? 'create' : 'update';
        _this.hoodie.trigger("remote:" + event, object);
        _this.hoodie.trigger("remote:" + event + ":" + doc.type, object);
        _this.hoodie.trigger("remote:" + event + ":" + doc.type + ":" + doc.id, object);
        _this.hoodie.trigger("remote:change", event, object);
        _this.hoodie.trigger("remote:change:" + doc.type, event, object);
        return _this.hoodie.trigger("remote:change:" + doc.type + ":" + doc.id, event, object);
      }));
    }
    return _results;
  };

  RemoteStore.prototype._handlePushSuccess = function(docs, pushedDocs) {
    var _this = this;
    return function() {
      var doc, i, options, update, _i, _len, _results;
      _results = [];
      for (i = _i = 0, _len = docs.length; _i < _len; i = ++_i) {
        doc = docs[i];
        update = {
          _rev: pushedDocs[i]._rev
        };
        options = {
          remote: true
        };
        _results.push(_this.hoodie.my.store.update(doc.type, doc.id, update, options));
      }
      return _results;
    };
  };

  return RemoteStore;

})(Hoodie.Store);
// Generated by CoffeeScript 1.3.3
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Hoodie.Account.RemoteStore = (function(_super) {

  __extends(RemoteStore, _super);

  RemoteStore.prototype._sync = true;

  function RemoteStore() {
    this.push = __bind(this.push, this);

    this.connect = __bind(this.connect, this);

    this.stopSyncing = __bind(this.stopSyncing, this);

    this.startSyncing = __bind(this.startSyncing, this);
    RemoteStore.__super__.constructor.apply(this, arguments);
    this.basePath = "/" + (encodeURIComponent(this.hoodie.my.account.db()));
    if (this.hoodie.my.config.get('_remote.sync') != null) {
      this._sync = this.hoodie.my.config.get('_remote.sync');
    }
    if (this.isContinuouslySyncing()) {
      this.startSyncing();
    }
  }

  RemoteStore.prototype.startSyncing = function() {
    this.hoodie.my.config.set('_remote.sync', this._sync = true);
    this.hoodie.on('account:signout', this.disconnect);
    this.hoodie.on('account:signin', this.connect);
    return this.connect();
  };

  RemoteStore.prototype.stopSyncing = function() {
    this.hoodie.my.config.set('_remote.sync', this._sync = false);
    this.hoodie.unbind('account:signin', this.connect);
    this.hoodie.unbind('account:signout', this.disconnect);
    return this.disconnect();
  };

  RemoteStore.prototype.connect = function() {
    var _this = this;
    return this.hoodie.my.account.authenticate().pipe(function() {
      return RemoteStore.__super__.connect.apply(_this, arguments);
    });
  };

  RemoteStore.prototype.getSinceNr = function(since) {
    return this.hoodie.my.config.get('_remote.since') || 0;
  };

  RemoteStore.prototype.setSinceNr = function(since) {
    return this.hoodie.my.config.set('_remote.since', since);
  };

  RemoteStore.prototype.push = function(docs) {
    if (!$.isArray(docs)) {
      docs = this.hoodie.my.store.changedDocs();
    }
    return RemoteStore.__super__.push.call(this, docs);
  };

  return RemoteStore;

})(Hoodie.RemoteStore);
// Generated by CoffeeScript 1.3.3
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

Hoodie.Config = (function() {

  Config.prototype.type = '$config';

  Config.prototype.id = 'hoodie';

  Config.prototype.cache = {};

  function Config(hoodie, options) {
    var _this = this;
    this.hoodie = hoodie;
    if (options == null) {
      options = {};
    }
    this.clear = __bind(this.clear, this);

    if (options.type) {
      this.type = options.type;
    }
    if (options.id) {
      this.id = options.id;
    }
    this.hoodie.my.store.find(this.type, this.id).done(function(obj) {
      return _this.cache = obj;
    });
    this.hoodie.on('account:signedOut', this.clear);
  }

  Config.prototype.set = function(key, value) {
    var isSilent, update;
    if (this.cache[key] === value) {
      return;
    }
    this.cache[key] = value;
    update = {};
    update[key] = value;
    isSilent = key.charAt(0) === '_';
    return this.hoodie.my.store.update(this.type, this.id, update, {
      silent: isSilent
    });
  };

  Config.prototype.get = function(key) {
    return this.cache[key];
  };

  Config.prototype.clear = function() {
    this.cache = {};
    return this.hoodie.my.store.destroy(this.type, this.id);
  };

  Config.prototype.remove = Config.prototype.set;

  return Config;

})();
// Generated by CoffeeScript 1.3.3
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

Hoodie.Email = (function() {

  function Email(hoodie) {
    this.hoodie = hoodie;
    this._handleEmailUpdate = __bind(this._handleEmailUpdate, this);

  }

  Email.prototype.send = function(emailAttributes) {
    var attributes, defer,
      _this = this;
    if (emailAttributes == null) {
      emailAttributes = {};
    }
    defer = this.hoodie.defer();
    attributes = $.extend({}, emailAttributes);
    if (!this._isValidEmail(emailAttributes.to)) {
      attributes.error = "Invalid email address (" + (attributes.to || 'empty') + ")";
      return defer.reject(attributes).promise();
    }
    this.hoodie.my.store.create('$email', attributes).then(function(obj) {
      return _this._handleEmailUpdate(defer, obj);
    });
    return defer.promise();
  };

  Email.prototype._isValidEmail = function(email) {
    if (email == null) {
      email = '';
    }
    return /@/.test(email);
  };

  Email.prototype._handleEmailUpdate = function(defer, attributes) {
    var _this = this;
    if (attributes == null) {
      attributes = {};
    }
    if (attributes.error) {
      return defer.reject(attributes);
    } else if (attributes.deliveredAt) {
      return defer.resolve(attributes);
    } else {
      return this.hoodie.one("remote:updated:$email:" + attributes.id, function(attributes) {
        return _this._handleEmailUpdate(defer, attributes);
      });
    }
  };

  return Email;

})();
// Generated by CoffeeScript 1.3.3

Hoodie.Errors = {
  INVALID_KEY: function(idOrType) {
    var key;
    key = idOrType.id ? 'id' : 'type';
    return new Error("invalid " + key + " '" + idOrType[key] + "': numbers and lowercase letters allowed only");
  },
  INVALID_ARGUMENTS: function(msg) {
    return new Error(msg);
  },
  NOT_FOUND: function(type, id) {
    return new Error("" + type + " with " + id + " could not be found");
  }
};
// Generated by CoffeeScript 1.3.3
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Hoodie.LocalStore = (function(_super) {

  __extends(LocalStore, _super);

  function LocalStore(hoodie) {
    this.hoodie = hoodie;
    this.clear = __bind(this.clear, this);

    if (!this.isPersistent()) {
      this.db = {
        getItem: function() {
          return null;
        },
        setItem: function() {
          return null;
        },
        removeItem: function() {
          return null;
        },
        key: function() {
          return null;
        },
        length: function() {
          return 0;
        },
        clear: function() {
          return null;
        }
      };
    }
    this.hoodie.on('account:signout', this.clear);
  }

  LocalStore.prototype.db = {
    getItem: function(key) {
      return window.localStorage.getItem(key);
    },
    setItem: function(key, value) {
      return window.localStorage.setItem(key, value);
    },
    removeItem: function(key) {
      return window.localStorage.removeItem(key);
    },
    key: function(nr) {
      return window.localStorage.key(nr);
    },
    length: function() {
      return window.localStorage.length;
    },
    clear: function() {
      return window.localStorage.clear();
    }
  };

  LocalStore.prototype.save = function(type, id, object, options) {
    var defer, isNew;
    if (options == null) {
      options = {};
    }
    defer = LocalStore.__super__.save.apply(this, arguments);
    if (this.hoodie.isPromise(defer)) {
      return defer;
    }
    object = $.extend({}, object);
    if (id) {
      isNew = typeof this._cached["" + type + "/" + id] !== 'object';
    } else {
      isNew = true;
      id = this.uuid();
    }
    if (isNew && this.hoodie.my.account) {
      object.$owner || (object.$owner = this.hoodie.my.account.owner);
    }
    if (options["public"] != null) {
      object.$public = options["public"];
    }
    if (options.remote) {
      object._syncedAt = this._now();
    } else if (!options.silent) {
      object.updatedAt = this._now();
      object.createdAt || (object.createdAt = object.updatedAt);
    }
    try {
      object = this.cache(type, id, object, options);
      defer.resolve(object, isNew).promise();
    } catch (error) {
      defer.reject(error).promise();
    }
    return defer.promise();
  };

  LocalStore.prototype.find = function(type, id) {
    var defer, object;
    defer = LocalStore.__super__.find.apply(this, arguments);
    if (this.hoodie.isPromise(defer)) {
      return defer;
    }
    try {
      object = this.cache(type, id);
      if (!object) {
        return defer.reject(Hoodie.Errors.NOT_FOUND(type, id)).promise();
      }
      defer.resolve(object);
    } catch (error) {
      defer.reject(error);
    }
    return defer.promise();
  };

  LocalStore.prototype.findAll = function(filter) {
    var currentType, defer, id, key, keys, obj, results, type;
    if (filter == null) {
      filter = function() {
        return true;
      };
    }
    defer = LocalStore.__super__.findAll.apply(this, arguments);
    if (this.hoodie.isPromise(defer)) {
      return defer;
    }
    keys = this._index();
    if (typeof filter === 'string') {
      type = filter;
      filter = function(obj) {
        return obj.type === type;
      };
    }
    try {
      results = (function() {
        var _i, _len, _ref, _results;
        _results = [];
        for (_i = 0, _len = keys.length; _i < _len; _i++) {
          key = keys[_i];
          if (!(this._isSemanticId(key))) {
            continue;
          }
          _ref = key.split('/'), currentType = _ref[0], id = _ref[1];
          obj = this.cache(currentType, id);
          if (filter(obj)) {
            _results.push(obj);
          } else {
            continue;
          }
        }
        return _results;
      }).call(this);
      defer.resolve(results).promise();
    } catch (error) {
      defer.reject(error).promise();
    }
    return defer.promise();
  };

  LocalStore.prototype.destroy = function(type, id, options) {
    var defer, key, object;
    if (options == null) {
      options = {};
    }
    defer = LocalStore.__super__.destroy.apply(this, arguments);
    if (this.hoodie.isPromise(defer)) {
      return defer;
    }
    object = this.cache(type, id);
    if (!object) {
      return defer.reject(Hoodie.Errors.NOT_FOUND(type, id)).promise();
    }
    if (object._syncedAt && !options.remote) {
      object._deleted = true;
      this.cache(type, id, object);
    } else {
      key = "" + type + "/" + id;
      this.db.removeItem(key);
      this._cached[key] = false;
      this.clearChanged(type, id);
    }
    return defer.resolve($.extend({}, object)).promise();
  };

  LocalStore.prototype.cache = function(type, id, object, options) {
    var key;
    if (object == null) {
      object = false;
    }
    if (options == null) {
      options = {};
    }
    key = "" + type + "/" + id;
    if (object) {
      this._cached[key] = $.extend(object, {
        type: type,
        id: id
      });
      this._setObject(type, id, object);
      if (options.remote) {
        this.clearChanged(type, id);
        return $.extend({}, this._cached[key]);
      }
    } else {
      if (this._cached[key] != null) {
        return $.extend({}, this._cached[key]);
      }
      this._cached[key] = this._getObject(type, id);
    }
    if (!options.silent) {
      if (this._cached[key] && (this._isDirty(this._cached[key]) || this._isMarkedAsDeleted(this._cached[key]))) {
        this.markAsChanged(type, id, this._cached[key]);
      } else {
        this.clearChanged(type, id);
      }
    }
    if (this._cached[key]) {
      return $.extend({}, this._cached[key]);
    } else {
      return this._cached[key];
    }
  };

  LocalStore.prototype.clearChanged = function(type, id) {
    var key;
    if (type && id) {
      key = "" + type + "/" + id;
      delete this._dirty[key];
    } else {
      this._dirty = {};
    }
    return this.hoodie.trigger('store:dirty');
  };

  LocalStore.prototype.isMarkedAsDeleted = function(type, id) {
    return this._isMarkedAsDeleted(this.cache(type, id));
  };

  LocalStore.prototype.markAsChanged = function(type, id, object) {
    var key, timeout,
      _this = this;
    key = "" + type + "/" + id;
    this._dirty[key] = object;
    this.hoodie.trigger('store:dirty');
    timeout = 2000;
    window.clearTimeout(this._dirtyTimeout);
    return this._dirtyTimeout = window.setTimeout((function() {
      return _this.hoodie.trigger('store:dirty:idle');
    }), timeout);
  };

  LocalStore.prototype.changedDocs = function() {
    var key, object, _ref, _results;
    _ref = this._dirty;
    _results = [];
    for (key in _ref) {
      object = _ref[key];
      _results.push(object);
    }
    return _results;
  };

  LocalStore.prototype.isDirty = function(type, id) {
    if (!type) {
      return $.isEmptyObject(this._dirty);
    }
    return this._isDirty(this.cache(type, id));
  };

  LocalStore.prototype.clear = function() {
    var defer;
    defer = this.hoodie.defer();
    try {
      this.db.clear();
      this._cached = {};
      this.clearChanged();
      defer.resolve();
    } catch (error) {
      defer.reject(error);
    }
    return defer.promise();
  };

  LocalStore.prototype.isPersistent = function() {
    try {
      if (!window.localStorage) {
        return false;
      }
      localStorage.setItem('Storage-Test', "1");
      if (localStorage.getItem('Storage-Test') !== "1") {
        return false;
      }
      localStorage.removeItem('Storage-Test');
    } catch (e) {
      return false;
    }
    return true;
  };

  LocalStore.prototype.uuid = function(len) {
    var chars, i, radix;
    if (len == null) {
      len = 7;
    }
    chars = '0123456789abcdefghijklmnopqrstuvwxyz'.split('');
    radix = chars.length;
    return ((function() {
      var _i, _results;
      _results = [];
      for (i = _i = 0; 0 <= len ? _i < len : _i > len; i = 0 <= len ? ++_i : --_i) {
        _results.push(chars[0 | Math.random() * radix]);
      }
      return _results;
    })()).join('');
  };

  LocalStore.prototype._setObject = function(type, id, object) {
    var key, store;
    key = "" + type + "/" + id;
    store = $.extend({}, object);
    delete store.type;
    delete store.id;
    return this.db.setItem(key, JSON.stringify(store));
  };

  LocalStore.prototype._getObject = function(type, id) {
    var json, key, obj;
    key = "" + type + "/" + id;
    json = this.db.getItem(key);
    if (json) {
      obj = JSON.parse(json);
      obj.type = type;
      obj.id = id;
      if (obj.createdAt) {
        obj.createdAt = new Date(Date.parse(obj.createdAt));
      }
      if (obj.updatedAt) {
        obj.updatedAt = new Date(Date.parse(obj.updatedAt));
      }
      if (obj._syncedAt) {
        obj._syncedAt = new Date(Date.parse(obj._syncedAt));
      }
      return obj;
    } else {
      return false;
    }
  };

  LocalStore.prototype._now = function() {
    return new Date;
  };

  LocalStore.prototype._isValidId = function(key) {
    return /^[a-z0-9\-]+$/.test(key);
  };

  LocalStore.prototype._isValidType = function(key) {
    return /^[a-z$][a-z0-9]+$/.test(key);
  };

  LocalStore.prototype._isSemanticId = function(key) {
    return /^[a-z$][a-z0-9]+\/[a-z0-9]+$/.test(key);
  };

  LocalStore.prototype._cached = {};

  LocalStore.prototype._dirty = {};

  LocalStore.prototype._isDirty = function(object) {
    if (!object._syncedAt) {
      return true;
    }
    if (!object.updatedAt) {
      return false;
    }
    return object._syncedAt.getTime() < object.updatedAt.getTime();
  };

  LocalStore.prototype._isMarkedAsDeleted = function(object) {
    return object._deleted === true;
  };

  LocalStore.prototype._index = function() {
    var i, _i, _ref, _results;
    _results = [];
    for (i = _i = 0, _ref = this.db.length(); 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
      _results.push(this.db.key(i));
    }
    return _results;
  };

  return LocalStore;

})(Hoodie.Store);
// Generated by CoffeeScript 1.3.3

Hoodie.User = (function() {

  function User(hoodie) {
    var _this = this;
    return function(username) {
      return hoodie.open(_this._userPublicStoreName(username));
    };
  }

  User.prototype._userPublicStoreName = function(username) {
    var dbName;
    dbName = username.toLowerCase().replace(/@/, "$").replace(/\./g, "_");
    return "" + dbName + "/public";
  };

  return User;

})();
// Generated by CoffeeScript 1.3.3

Hoodie.Global = (function() {

  function Global(hoodie) {
    return hoodie.open("global");
  }

  return Global;

})();
// Generated by CoffeeScript 1.3.3
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

Hoodie.Share = (function() {

  function Share(hoodie) {
    var api;
    this.hoodie = hoodie;
    this.open = __bind(this.open, this);

    api = this.open;
    this.instance = Hoodie.Share.Instance;
    this.instance.hoodie = this.hoodie;
    $.extend(api, this);
    return api;
  }

  Share.prototype.open = function(share_id, options) {
    return new this.instance({
      id: share_id
    }, options);
  };

  Share.prototype.create = function(attributes) {
    var share;
    if (attributes == null) {
      attributes = {};
    }
    share = new this.instance(attributes);
    return share.save();
  };

  Share.prototype.find = function(id) {
    var _this = this;
    return this.hoodie.my.store.find('$share', id).pipe(function(object) {
      return new _this.instance(object);
    });
  };

  Share.prototype.findAll = function() {
    var _this = this;
    return this.hoodie.my.store.findAll('$share').pipe(function(objects) {
      var obj, _i, _len, _results;
      _results = [];
      for (_i = 0, _len = objects.length; _i < _len; _i++) {
        obj = objects[_i];
        _results.push(new _this.instance(obj));
      }
      return _results;
    });
  };

  Share.prototype.findOrCreate = function(id, attributes) {
    var _this = this;
    return this.hoodie.my.store.findOrCreate('$share', id, attributes).pipe(function(object) {
      return new _this.instance(object);
    });
  };

  Share.prototype.save = function(id, attributes) {
    var _this = this;
    return this.hoodie.my.store.save('$share', id, attributes).pipe(function(object) {
      return new _this.instance(object);
    });
  };

  Share.prototype.update = function(id, changed_attributes) {
    var _this = this;
    return this.hoodie.my.store.update('$share', id, changed_attributes).pipe(function(object) {
      return new _this.instance(object);
    });
  };

  Share.prototype.updateAll = function(changed_attributes) {
    var _this = this;
    return this.hoodie.my.store.updateAll('$share', changed_attributes).pipe(function(objects) {
      var obj, _i, _len, _results;
      _results = [];
      for (_i = 0, _len = objects.length; _i < _len; _i++) {
        obj = objects[_i];
        _results.push(new _this.instance(obj));
      }
      return _results;
    });
  };

  Share.prototype.destroy = function(id) {
    var _this = this;
    return this.find(id).pipe(function(obj) {
      var share;
      share = new _this.instance(obj);
      return share.destroy();
    });
  };

  Share.prototype["delete"] = function() {
    return this.destroy.apply(this, arguments);
  };

  Share.prototype.destroyAll = function() {
    var _this = this;
    return this.findAll().pipe(function(objects) {
      var obj, share, _i, _len, _results;
      _results = [];
      for (_i = 0, _len = objects.length; _i < _len; _i++) {
        obj = objects[_i];
        share = new _this.instance(obj);
        _results.push(share.destroy());
      }
      return _results;
    });
  };

  Share.prototype.deleteAll = function() {
    return this.destroyAll.apply(this, arguments);
  };

  return Share;

})();
// Generated by CoffeeScript 1.3.3
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  __slice = [].slice;

Hoodie.Share.Instance = (function(_super) {

  __extends(Instance, _super);

  function Instance(options) {
    var access, continuous, id, password;
    if (options == null) {
      options = {};
    }
    this._isMySharedObjectAndChanged = __bind(this._isMySharedObjectAndChanged, this);

    this._isMySharedObject = __bind(this._isMySharedObject, this);

    this._toggle = __bind(this._toggle, this);

    this._remove = __bind(this._remove, this);

    this._add = __bind(this._add, this);

    this.destroy = __bind(this.destroy, this);

    this.sync = __bind(this.sync, this);

    this.get = __bind(this.get, this);

    this.set = __bind(this.set, this);

    this.hoodie = this.constructor.hoodie;
    id = options.id, access = options.access, continuous = options.continuous, password = options.password;
    access || (access = false);
    this.set({
      id: id,
      access: access,
      continuous: continuous,
      password: password
    });
    this.id || (this.id = this.hoodie.my.store.uuid());
  }

  Instance.prototype._memory = {};

  Instance.prototype.set = function(key, value) {
    var _key, _ref;
    if (typeof key === 'object') {
      for (_key in key) {
        value = key[_key];
        this[_key] = this._memory[_key] = value;
      }
    } else {
      this[key] = this._memory[key] = value;
    }
    if ((_ref = this.invitees) != null ? _ref.length : void 0) {
      this["private"] = this._memory["private"] = true;
    }
    return void 0;
  };

  Instance.prototype.get = function(key) {
    return this[key];
  };

  Instance.prototype.save = function(update, options) {
    var _handleUpdate,
      _this = this;
    if (update == null) {
      update = {};
    }
    this.hoodie.my.account.anonymousSignUp();
    if (update) {
      this.set(update);
    }
    _handleUpdate = function(properties, wasCreated) {
      _this._memory = {};
      $.extend(_this, properties);
      return _this;
    };
    return this.hoodie.my.store.update("$share", this.id, this._memory, options).pipe(_handleUpdate);
  };

  Instance.prototype.add = function(objects, sharedAttributes) {
    return this.toggle(objects, sharedAttributes || true);
    /*
        filter = sharedAttributes or true
    
        # normalize input
        unless @hoodie.isPromise(objects) or $.isArray(objects)
          objects = [objects]
    
        @hoodie.my.store.updateAll objects, (obj) => 
          obj.$shares or= {}
          obj.$shares[@id] = filter
    
          $shares: obj.$shares
    */

  };

  Instance.prototype.remove = function(objects) {
    return this.toggle(objects, false);
  };

  Instance.prototype.toggle = function(objects, filter) {
    var updateMethod;
    if (!(this.hoodie.isPromise(objects) || $.isArray(objects))) {
      objects = [objects];
    }
    updateMethod = (function() {
      switch (filter) {
        case true:
          return this._add(filter);
        case false:
          return this._remove;
        default:
          return this._toggle;
      }
    }).call(this);
    return this.hoodie.my.store.updateAll(objects, updateMethod);
  };

  Instance.prototype.sync = function() {
    var _this = this;
    return this.save().pipe(this.hoodie.my.store.findAll(this._isMySharedObjectAndChanged).pipe(function(sharedObjectsThatChanged) {
      return _this.hoodie.my.remote.sync(sharedObjectsThatChanged).then(_this._handleRemoteChanges);
    }));
  };

  Instance.prototype.destroy = function() {
    var _this = this;
    return this.remove(this.hoodie.my.store.findAll(this._isMySharedObject)).then(function() {
      return _this.hoodie.my.store.destroy("$share", _this.id);
    });
  };

  Instance.prototype._add = function(filter) {
    var _this = this;
    return function(obj) {
      obj.$shares || (obj.$shares = {});
      obj.$shares[_this.id] = filter;
      return {
        $shares: obj.$shares
      };
    };
  };

  Instance.prototype._remove = function(obj) {
    if (!obj.$shares) {
      return {};
    }
    delete obj.$shares[this.id];
    if ($.isEmptyObject(obj.$shares)) {
      obj.$shares = void 0;
    }
    return {
      $shares: obj.$shares
    };
  };

  Instance.prototype._toggle = function(obj) {
    var doAdd;
    try {
      doAdd = ~obj.$shares.indexOf(this.id);
    } catch (e) {
      doAdd = true;
    }
    if (doAdd) {
      return this._add(obj);
    } else {
      return this._remove(obj);
    }
  };

  Instance.prototype._isMySharedObject = function(obj) {
    var _ref;
    return ((_ref = obj.$shares) != null ? _ref[this.id] : void 0) != null;
  };

  Instance.prototype._isMySharedObjectAndChanged = function(obj) {
    var belongsToMe, _ref;
    belongsToMe = obj.id === this.id || (((_ref = obj.$shares) != null ? _ref[this.id] : void 0) != null);
    return belongsToMe && this.hoodie.my.store.isDirty(obj.type, obj.id);
  };

  Instance.prototype._handleRemoteChanges = function() {
    return console.log.apply(console, ['_handleRemoteChanges'].concat(__slice.call(arguments)));
  };

  return Instance;

})(Hoodie.RemoteStore);
