// Generated by CoffeeScript 1.3.3
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

Hoodie.Account = (function() {

  Account.prototype.username = void 0;

  function Account(hoodie) {
    this.hoodie = hoodie;
    this._checkPasswordResetStatus = __bind(this._checkPasswordResetStatus, this);

    this._handleSignOutSuccess = __bind(this._handleSignOutSuccess, this);

    this._handleSignInSuccess = __bind(this._handleSignInSuccess, this);

    this._delayedSignIn = __bind(this._delayedSignIn, this);

    this._handleSignUpSucces = __bind(this._handleSignUpSucces, this);

    this._handleRequestError = __bind(this._handleRequestError, this);

    this._handleAuthenticateSuccess = __bind(this._handleAuthenticateSuccess, this);

    this.fetch = __bind(this.fetch, this);

    this.authenticate = __bind(this.authenticate, this);

    this.username = this.hoodie.my.config.get('_account.username');
    this.owner = this.hoodie.my.config.get('_account.owner');
    if (!this.owner) {
      this.owner = this.hoodie.my.store.uuid();
      this.hoodie.my.config.set('_account.owner', this.owner);
    }
    this._checkPasswordResetStatus();
  }

  Account.prototype.authenticate = function() {
    if (!this.username) {
      return this.hoodie.defer().reject().promise();
    }
    if (this._authenticated === true) {
      return this.hoodie.defer().resolve(this.username).promise();
    }
    if (this._authenticated === false) {
      return this.hoodie.defer().reject().promise();
    }
    return this.hoodie.request('GET', "/_session").pipe(this._handleAuthenticateSuccess, this._handleRequestError);
  };

  Account.prototype.signUp = function(username, password) {
    var currentPassword, defer, key, options,
      _this = this;
    if (password == null) {
      password = '';
    }
    if (this.hasAnonymousAccount()) {
      defer = this.hoodie.defer();
      currentPassword = this.hoodie.my.config.get('_account.anonymousPassword');
      this._changeUserNameAndPassword(currentPassword, username, password).fail(defer.reject).done(function() {
        _this.hoodie.my.config.remove('_account.anonymousPassword');
        return defer.resolve.apply(defer, arguments);
      });
      return defer.promise();
    } else {
      key = "" + this._prefix + ":" + username;
      options = {
        data: JSON.stringify({
          _id: key,
          name: username,
          type: 'user',
          roles: [],
          password: password,
          $owner: this.owner,
          database: this.db()
        }),
        contentType: 'application/json'
      };
      return this.hoodie.request('PUT', "/_users/" + (encodeURIComponent(key)), options).pipe(this._handleSignUpSucces(username, password), this._handleRequestError);
    }
  };

  Account.prototype.anonymousSignUp = function() {
    var password, username;
    password = this.hoodie.my.store.uuid(10);
    username = "anonymous/" + this.owner;
    this.signUp(username, password);
    return this.hoodie.my.config.set('_account.anonymousPassword', password);
  };

  Account.prototype.hasAnonymousAccount = function() {
    return this.hoodie.my.config.get('_account.anonymousPassword') != null;
  };

  Account.prototype.signIn = function(username, password) {
    var defer, options;
    if (password == null) {
      password = '';
    }
    defer = this.hoodie.defer();
    options = {
      data: {
        name: username,
        password: password
      }
    };
    return this.hoodie.request('POST', '/_session', options).pipe(this._handleSignInSuccess).then(defer.resolve, defer.reject);
  };

  Account.prototype.login = Account.prototype.signIn;

  Account.prototype.signOut = function() {
    this.hoodie.my.remote.disconnect();
    return this.hoodie.request('DELETE', '/_session').pipe(this._handleSignOutSuccess);
  };

  Account.prototype.logout = Account.prototype.signOut;

  Account.prototype.on = function(event, cb) {
    return this.hoodie.on("account:" + event, cb);
  };

  Account.prototype.db = function() {
    return "user/" + this.owner;
  };

  Account.prototype.fetch = function(username) {
    var defer, key,
      _this = this;
    if (username == null) {
      username = this.username;
    }
    defer = this.hoodie.defer();
    if (!username) {
      defer.reject({
        error: "unauthenticated",
        reason: "not logged in"
      });
      return defer.promise();
    }
    key = "" + this._prefix + ":" + username;
    this.hoodie.request('GET', "/_users/" + (encodeURIComponent(key)), {
      success: function(response) {
        _this._doc = response;
        return defer.resolve(response);
      },
      error: function(xhr) {
        var error;
        try {
          error = JSON.parse(xhr.responseText);
        } catch (e) {
          error = {
            error: xhr.responseText || "unknown"
          };
        }
        return defer.reject(error);
      }
    });
    return defer.promise();
  };

  Account.prototype.changePassword = function(currentPassword, newPassword) {
    var data, defer, key,
      _this = this;
    defer = this.hoodie.defer();
    if (!this.username) {
      defer.reject({
        error: "unauthenticated",
        reason: "not logged in"
      });
      return defer.promise();
    }
    key = "" + this._prefix + ":" + this.username;
    data = $.extend({}, this._doc);
    delete data.salt;
    delete data.password_sha;
    data.password = newPassword;
    return this.hoodie.request('PUT', "/_users/" + (encodeURIComponent(key)), {
      data: JSON.stringify(data),
      contentType: "application/json",
      success: function(response) {
        return window.setTimeout((function() {
          _this.hoodie.my.remote.disconnect();
          return _this.signIn(_this.username, newPassword).then(defer.resolve, defer.reject);
        }), 1000);
      },
      error: function(xhr) {
        var error;
        try {
          error = JSON.parse(xhr.responseText);
        } catch (e) {
          error = {
            error: xhr.responseText || "unknown"
          };
        }
        return defer.reject(error);
      }
    });
  };

  Account.prototype.resetPassword = function(username) {
    var data, defer, key, resetPasswordId,
      _this = this;
    defer = this.hoodie.defer();
    if (resetPasswordId = this.hoodie.my.config.get('_account.resetPasswordId')) {
      return this._checkPasswordResetStatus();
    }
    resetPasswordId = "" + username + "/" + (this.hoodie.my.store.uuid());
    this.hoodie.my.config.set('_account.resetPasswordId', resetPasswordId);
    key = "" + this._prefix + ":$passwordReset/" + resetPasswordId;
    data = {
      _id: key,
      name: "$passwordReset/" + resetPasswordId,
      type: 'user',
      password: resetPasswordId,
      createdAt: new Date,
      updatedAt: new Date
    };
    this.hoodie.request('PUT', "/_users/" + (encodeURIComponent(key)), {
      data: JSON.stringify(data),
      contentType: "application/json",
      success: function(response) {
        defer.resolve();
        return _this._checkPasswordResetStatus();
      },
      error: function(xhr) {
        var error;
        try {
          error = JSON.parse(xhr.responseText);
        } catch (e) {
          error = {
            error: xhr.responseText || "unknown"
          };
        }
        return defer.reject(error);
      }
    });
    return defer.promise();
  };

  Account.prototype.changeUsername = function(currentPassword, newUsername) {
    return this._changeUserNameAndPassword(currentPassword, newUsername);
  };

  Account.prototype.destroy = function() {
    var _this = this;
    this.hoodie.my.remote.disconnect();
    return this.fetch().pipe(function() {
      var key;
      key = "" + _this._prefix + ":" + _this.username;
      _this._doc._deleted = true;
      return _this.hoodie.request('PUT', "/_users/" + (encodeURIComponent(key)), {
        data: JSON.stringify(_this._doc),
        contentType: 'application/json'
      });
    });
  };

  Account.prototype._prefix = 'org.couchdb.user';

  Account.prototype._doc = {};

  Account.prototype._handleAuthenticateSuccess = function(response) {
    var defer;
    defer = this.hoodie.defer();
    if (response.userCtx.name) {
      this._authenticated = true;
      this.username = response.userCtx.name;
      this.owner = response.userCtx.roles[0];
      this.hoodie.my.config.set('_account.username', this.username);
      this.hoodie.my.config.set('_account.owner', this.owner);
      defer.resolve(this.username);
    } else {
      this._authenticated = false;
      this.hoodie.trigger('account:error:unauthenticated');
      defer.reject();
    }
    return defer.promise();
  };

  Account.prototype._handleRequestError = function(xhr) {
    var error;
    try {
      error = JSON.parse(xhr.responseText);
    } catch (e) {
      error = {
        error: xhr.responseText || "unknown"
      };
    }
    return this.hoodie.defer().reject(error).promise();
  };

  Account.prototype._handleSignUpSucces = function(username, password) {
    var defer,
      _this = this;
    defer = this.hoodie.defer();
    return function(response) {
      _this.hoodie.trigger('account:signup', username);
      _this._doc._rev = response.rev;
      return _this._delayedSignIn(username, password);
    };
  };

  Account.prototype._delayedSignIn = function(username, password) {
    var defer,
      _this = this;
    defer = this.hoodie.defer();
    window.setTimeout((function() {
      var promise;
      promise = _this.signIn(username, password);
      promise.done(defer.resolve);
      return promise.fail(function(error) {
        if (error.error === 'unconfirmed') {
          return _this._delayedSignIn(username, password);
        } else {
          return defer.reject.apply(defer, arguments);
        }
      });
    }), 300);
    return defer.promise();
  };

  Account.prototype._handleSignInSuccess = function(response) {
    var defer,
      _this = this;
    defer = this.hoodie.defer();
    if (~response.roles.indexOf("error")) {
      this.fetch(response.name).fail(defer.reject).done(function() {
        return defer.reject({
          error: "error",
          reason: _this._doc.$error
        });
      });
      return defer.promise();
    }
    if (!~response.roles.indexOf("confirmed")) {
      return defer.reject({
        error: "unconfirmed",
        reason: "account has not been confirmed yet"
      });
    }
    this.username = response.name;
    this._authenticated = true;
    this.owner = response.roles[0];
    this.hoodie.my.config.set('_account.username', this.username);
    this.hoodie.my.config.set('_account.owner', this.owner);
    this.hoodie.trigger('account:signin', this.username);
    this.fetch();
    return defer.resolve(this.username, response);
  };

  Account.prototype._handleSignOutSuccess = function() {
    delete this.username;
    this.hoodie.my.config.clear();
    this._authenticated = false;
    return this.hoodie.trigger('account:signout');
  };

  Account.prototype._checkPasswordResetStatus = function() {
    var auth, defer, hash, resetPasswordId, username,
      _this = this;
    defer = this.hoodie.defer();
    resetPasswordId = this.hoodie.my.config.get('_account.resetPasswordId');
    if (!resetPasswordId) {
      return defer.reject({
        error: "missing"
      }).promise();
    }
    defer.done(function() {
      _this.hoodie.my.config.remove('_account.resetPasswordId');
      return _this.hoodie.trigger('account:password_reset:success');
    });
    defer.fail(function(error) {
      if (error.error === 'pending') {
        window.setTimeout(_this._checkPasswordResetStatus, 1000);
        return;
      }
      _this.hoodie.my.config.remove('_account.resetPasswordId');
      return _this.hoodie.trigger('account:password_reset:error');
    });
    username = "$passwordReset/" + resetPasswordId;
    hash = btoa("" + username + ":" + resetPasswordId);
    auth = "Basic " + hash;
    this.hoodie.request('GET', "/_users/" + (encodeURIComponent("" + this._prefix + ":" + username)), {
      headers: {
        Authorization: auth
      },
      success: function(response) {
        if (response.$error) {
          return defer.reject({
            error: response.$error
          });
        }
        return defer.reject({
          error: 'pending'
        });
      },
      error: function(xhr) {
        var error;
        if (xhr.status === 401) {
          return defer.resolve();
        }
        try {
          error = JSON.parse(xhr.responseText);
        } catch (e) {
          error = {
            error: xhr.responseText || "unknown"
          };
        }
        return defer.reject(error);
      }
    });
    return defer.promise();
  };

  Account.prototype._changeUserNameAndPassword = function(currentPassword, newUsername, newPassword) {
    var defer,
      _this = this;
    defer = this.hoodie.defer();
    this.authenticate().pipe(function() {
      var data, key, reqPromise;
      key = "" + _this._prefix + ":" + _this.username;
      data = $.extend({}, _this._doc);
      data.$newUsername = newUsername;
      if (newPassword) {
        delete data.salt;
        delete data.password_sha;
        data.password = newPassword;
      }
      reqPromise = _this.hoodie.request('PUT', "/_users/" + (encodeURIComponent(key)), {
        data: JSON.stringify(data),
        contentType: 'application/json'
      });
      reqPromise.fail(defer.reject);
      return reqPromise.done(function() {
        _this.hoodie.my.remote.disconnect();
        return window.setTimeout((function() {
          return _this.signIn(newUsername, newPassword || currentPassword).then(defer.resolve, defer.reject);
        }), 1000);
      });
    });
    return defer.promise();
  };

  return Account;

})();
