// Generated by CoffeeScript 1.3.3

define('hoodie/config', function() {
  var Config;
  return Config = (function() {

    Config.prototype.type = '$config';

    Config.prototype.id = 'hoodie';

    Config.prototype.cache = {};

    function Config(hoodie, options) {
      var _this = this;
      this.hoodie = hoodie;
      if (options == null) {
        options = {};
      }
      if (options.type) {
        this.type = options.type;
      }
      if (options.id) {
        this.id = options.id;
      }
      this.hoodie.store.load(this.type, this.id).done(function(obj) {
        return _this.cache = obj;
      });
    }

    Config.prototype.set = function(key, value) {
      var update;
      if (this.cache[key] === value) {
        return;
      }
      this.cache[key] = value;
      update = {};
      update[key] = value;
      if (key.charAt(0) === '_') {
        return this.hoodie.store.update(this.type, this.id, update, {
          silent: true
        });
      } else {
        return this.hoodie.store.update(this.type, this.id, update);
      }
    };

    Config.prototype.get = function(key) {
      return this.cache[key];
    };

    Config.prototype.remove = Config.prototype.set;

    return Config;

  })();
});
