// Generated by CoffeeScript 1.3.3
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  __slice = [].slice;

Hoodie.LocalStore = (function(_super) {

  __extends(LocalStore, _super);

  LocalStore.prototype.idleTimeout = 2000;

  function LocalStore(hoodie) {
    this.hoodie = hoodie;
    this.clear = __bind(this.clear, this);

    this.markAllAsChanged = __bind(this.markAllAsChanged, this);

    if (!this.isPersistent()) {
      this.db = {
        getItem: function() {
          return null;
        },
        setItem: function() {
          return null;
        },
        removeItem: function() {
          return null;
        },
        key: function() {
          return null;
        },
        length: 0,
        clear: function() {
          return null;
        }
      };
    }
    this.hoodie.on('account:signout', this.clear);
    this.hoodie.on('account:signup', this.markAllAsChanged);
    this._promiseApi.hoodie = this.hoodie;
    this._bootstrap();
  }

  LocalStore.prototype.db = {
    getItem: function(key) {
      return window.localStorage.getItem(key);
    },
    setItem: function(key, value) {
      return window.localStorage.setItem(key, value);
    },
    removeItem: function(key) {
      return window.localStorage.removeItem(key);
    },
    key: function(nr) {
      return window.localStorage.key(nr);
    },
    length: function() {
      return window.localStorage.length;
    },
    clear: function() {
      return window.localStorage.clear();
    }
  };

  LocalStore.prototype.save = function(type, id, object, options) {
    var currentObject, defer, event, isNew, key;
    if (options == null) {
      options = {};
    }
    defer = LocalStore.__super__.save.apply(this, arguments);
    if (this.hoodie.isPromise(defer)) {
      return this._decoratePromise(defer);
    }
    object = $.extend(true, {}, object);
    if (id) {
      currentObject = this.cache(type, id);
      isNew = typeof currentObject !== 'object';
    } else {
      isNew = true;
      id = this.hoodie.uuid();
    }
    if (isNew && this.hoodie.account) {
      object.$createdBy || (object.$createdBy = this.hoodie.account.ownerHash);
    }
    if (!isNew) {
      delete object.$updatedBy;
      for (key in currentObject) {
        if (!object.hasOwnProperty(key)) {
          switch (key.charAt(0)) {
            case '_':
              if (options.remote) {
                object[key] = currentObject[key];
              }
              break;
            case '$':
              if (!options.remote) {
                object[key] = currentObject[key];
              }
          }
        }
      }
    }
    if (options.remote) {
      object._$syncedAt = this._now();
    } else if (!options.silent) {
      object.$updatedAt = this._now();
      object.$createdAt || (object.$createdAt = object.$updatedAt);
    }
    try {
      object = this.cache(type, id, object, options);
      defer.resolve(object, isNew).promise();
      event = isNew ? 'add' : 'update';
      this._triggerEvents(event, object, options);
    } catch (error) {
      defer.reject(error).promise();
    }
    return this._decoratePromise(defer.promise());
  };

  LocalStore.prototype.find = function(type, id) {
    var defer, object;
    defer = LocalStore.__super__.find.apply(this, arguments);
    if (this.hoodie.isPromise(defer)) {
      return this._decoratePromise(defer);
    }
    try {
      object = this.cache(type, id);
      if (!object) {
        defer.reject(Hoodie.Errors.NOT_FOUND(type, id)).promise();
      }
      defer.resolve(object);
    } catch (error) {
      defer.reject(error);
    }
    return this._decoratePromise(defer.promise());
  };

  LocalStore.prototype.findAll = function(filter) {
    var currentType, defer, id, key, keys, obj, results, type;
    if (filter == null) {
      filter = function() {
        return true;
      };
    }
    defer = LocalStore.__super__.findAll.apply(this, arguments);
    if (this.hoodie.isPromise(defer)) {
      return this._decoratePromise(defer);
    }
    keys = this._index();
    if (typeof filter === 'string') {
      type = filter;
      filter = function(obj) {
        return obj.$type === type;
      };
    }
    try {
      results = (function() {
        var _i, _len, _ref, _results;
        _results = [];
        for (_i = 0, _len = keys.length; _i < _len; _i++) {
          key = keys[_i];
          if (!(this._isSemanticId(key))) {
            continue;
          }
          _ref = key.split('/'), currentType = _ref[0], id = _ref[1];
          obj = this.cache(currentType, id);
          if (obj && filter(obj)) {
            _results.push(obj);
          } else {
            continue;
          }
        }
        return _results;
      }).call(this);
      defer.resolve(results).promise();
    } catch (error) {
      defer.reject(error).promise();
    }
    return this._decoratePromise(defer.promise());
  };

  LocalStore.prototype.remove = function(type, id, options) {
    var defer, key, object, promise;
    if (options == null) {
      options = {};
    }
    defer = LocalStore.__super__.remove.apply(this, arguments);
    if (this.hoodie.isPromise(defer)) {
      return this._decoratePromise(defer);
    }
    object = this.cache(type, id);
    if (!object) {
      return this._decoratePromise(defer.reject(Hoodie.Errors.NOT_FOUND(type, id)).promise());
    }
    if (object._$syncedAt && !options.remote) {
      object._deleted = true;
      this.cache(type, id, object);
    } else {
      key = "" + type + "/" + id;
      this.db.removeItem(key);
      this._cached[key] = false;
      this.clearChanged(type, id);
    }
    this._triggerEvents("remove", object, options);
    promise = defer.resolve($.extend(true, {}, object)).promise();
    return this._decoratePromise(promise);
  };

  LocalStore.prototype.update = function() {
    return this._decoratePromise(LocalStore.__super__.update.apply(this, arguments));
  };

  LocalStore.prototype.updateAll = function() {
    return this._decoratePromise(LocalStore.__super__.updateAll.apply(this, arguments));
  };

  LocalStore.prototype.removeAll = function() {
    return this._decoratePromise(LocalStore.__super__.removeAll.apply(this, arguments));
  };

  LocalStore.prototype.cache = function(type, id, object, options) {
    var key;
    if (object == null) {
      object = false;
    }
    if (options == null) {
      options = {};
    }
    key = "" + type + "/" + id;
    if (object) {
      $.extend(true, object, {
        $type: type,
        id: id
      });
      this._setObject(type, id, object);
      if (options.remote) {
        this.clearChanged(type, id);
        this._cached[key] = object;
        return $.extend(true, {}, this._cached[key]);
      }
    } else {
      if (this._cached[key] === false) {
        return false;
      }
      if (this._cached[key]) {
        return $.extend(true, {}, this._cached[key]);
      }
      object = this._getObject(type, id);
    }
    if (object === void 0) {
      return;
    }
    if (object === false) {
      this.clearChanged(type, id);
      this._cached[key] = false;
      return false;
    }
    if (this._isMarkedAsDeleted(object)) {
      this.markAsChanged(type, id, object, options);
      this._cached[key] = false;
      return false;
    }
    this._cached[key] = object;
    if (this._isDirty(object)) {
      this.markAsChanged(type, id, object, options);
    } else {
      this.clearChanged(type, id);
    }
    return $.extend(true, {}, this._cached[key]);
  };

  LocalStore.prototype.clearChanged = function(type, id) {
    var key;
    if (type && id) {
      key = "" + type + "/" + id;
      delete this._dirty[key];
    } else {
      this._dirty = {};
    }
    this._saveDirtyIds();
    return window.clearTimeout(this._dirtyTimeout);
  };

  LocalStore.prototype.isMarkedAsDeleted = function(type, id) {
    return this._isMarkedAsDeleted(this.cache(type, id));
  };

  LocalStore.prototype.markAsChanged = function(type, id, object, options) {
    var key;
    if (options == null) {
      options = {};
    }
    key = "" + type + "/" + id;
    this._dirty[key] = object;
    this._saveDirtyIds();
    if (options.silent) {
      return;
    }
    return this._trigger_dirty_and_idle_events();
  };

  LocalStore.prototype.markAllAsChanged = function() {
    var _this = this;
    return this.findAll().pipe(function(objects) {
      var key, object, _i, _len;
      for (_i = 0, _len = objects.length; _i < _len; _i++) {
        object = objects[_i];
        key = "" + object.$type + "/" + object.id;
        _this._dirty[key] = object;
      }
      _this._saveDirtyIds();
      return _this._trigger_dirty_and_idle_events();
    });
  };

  LocalStore.prototype.changedDocs = function() {
    var id, key, object, type, _ref, _ref1, _results;
    _ref = this._dirty;
    _results = [];
    for (key in _ref) {
      object = _ref[key];
      _ref1 = key.split('/'), type = _ref1[0], id = _ref1[1];
      object.$type = type;
      object.id = id;
      _results.push(object);
    }
    return _results;
  };

  LocalStore.prototype.isDirty = function(type, id) {
    if (!type) {
      return $.isEmptyObject(this._dirty);
    }
    return this._isDirty(this.cache(type, id));
  };

  LocalStore.prototype.clear = function() {
    var defer, key, keys, results;
    defer = this.hoodie.defer();
    try {
      keys = this._index();
      results = (function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = keys.length; _i < _len; _i++) {
          key = keys[_i];
          if (this._isSemanticId(key)) {
            _results.push(this.db.removeItem(key));
          }
        }
        return _results;
      }).call(this);
      this._cached = {};
      this.clearChanged();
      defer.resolve();
      this.trigger("clear");
    } catch (error) {
      defer.reject(error);
    }
    return defer.promise();
  };

  LocalStore.prototype.isPersistent = function() {
    try {
      if (!window.localStorage) {
        return false;
      }
      localStorage.setItem('Storage-Test', "1");
      if (localStorage.getItem('Storage-Test') !== "1") {
        return false;
      }
      localStorage.removeItem('Storage-Test');
    } catch (e) {
      return false;
    }
    return true;
  };

  LocalStore.prototype.trigger = function() {
    var event, parameters, _ref;
    event = arguments[0], parameters = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    return (_ref = this.hoodie).trigger.apply(_ref, ["store:" + event].concat(__slice.call(parameters)));
  };

  LocalStore.prototype.on = function(event, data) {
    event = event.replace(/(^| )([^ ]+)/g, "$1store:$2");
    return this.hoodie.on(event, data);
  };

  LocalStore.prototype.decoratePromises = function(methods) {
    return $.extend(this._promiseApi, methods);
  };

  LocalStore.prototype._bootstrap = function() {
    var id, key, keys, obj, type, _i, _len, _ref, _results;
    keys = this.db.getItem('_dirty');
    if (!keys) {
      return;
    }
    _results = [];
    for (_i = 0, _len = keys.length; _i < _len; _i++) {
      key = keys[_i];
      _ref = key.split('/'), type = _ref[0], id = _ref[1];
      _results.push(obj = this.cache(type, id));
    }
    return _results;
  };

  LocalStore.prototype._setObject = function(type, id, object) {
    var key, store;
    key = "" + type + "/" + id;
    store = $.extend({}, object);
    delete store.$type;
    delete store.id;
    return this.db.setItem(key, JSON.stringify(store));
  };

  LocalStore.prototype._getObject = function(type, id) {
    var json, key, obj;
    key = "" + type + "/" + id;
    json = this.db.getItem(key);
    if (json) {
      obj = JSON.parse(json);
      obj.$type = type;
      obj.id = id;
      if (obj.$createdAt) {
        obj.$createdAt = new Date(Date.parse(obj.$createdAt));
      }
      if (obj.$updatedAt) {
        obj.$updatedAt = new Date(Date.parse(obj.$updatedAt));
      }
      if (obj._$syncedAt) {
        obj._$syncedAt = new Date(Date.parse(obj._$syncedAt));
      }
      return obj;
    } else {
      return false;
    }
  };

  LocalStore.prototype._saveDirtyIds = function() {
    var ids;
    if ($.isEmptyObject(this._dirty)) {
      return this.db.removeItem('_dirty');
    } else {
      ids = Object.keys(this._dirty);
      return this.db.setItem('_dirty', ids.join(','));
    }
  };

  LocalStore.prototype._now = function() {
    return new Date;
  };

  LocalStore.prototype._isValidId = function(key) {
    return /^[a-z0-9\-]+$/.test(key);
  };

  LocalStore.prototype._isValidType = function(key) {
    return /^[a-z$][a-z0-9]+$/.test(key);
  };

  LocalStore.prototype._isSemanticId = function(key) {
    return /^[a-z$][a-z0-9]+\/[a-z0-9]+$/.test(key);
  };

  LocalStore.prototype._cached = {};

  LocalStore.prototype._dirty = {};

  LocalStore.prototype._isDirty = function(object) {
    if (!object.$updatedAt) {
      return false;
    }
    if (!object._$syncedAt) {
      return true;
    }
    return object._$syncedAt.getTime() < object.$updatedAt.getTime();
  };

  LocalStore.prototype._isMarkedAsDeleted = function(object) {
    return object._deleted === true;
  };

  LocalStore.prototype._index = function() {
    var i, _i, _ref, _results;
    _results = [];
    for (i = _i = 0, _ref = this.db.length(); 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
      _results.push(this.db.key(i));
    }
    return _results;
  };

  LocalStore.prototype._triggerEvents = function(event, object, options) {
    this.trigger(event, object, options);
    this.trigger("" + event + ":" + object.$type, object, options);
    if (event !== 'new') {
      this.trigger("" + event + ":" + object.$type + ":" + object.id, object, options);
    }
    this.trigger("change", event, object, options);
    this.trigger("change:" + object.$type, event, object, options);
    if (event !== 'new') {
      return this.trigger("change:" + object.$type + ":" + object.id, event, object, options);
    }
  };

  LocalStore.prototype._trigger_dirty_and_idle_events = function() {
    var _this = this;
    this.trigger('dirty');
    window.clearTimeout(this._dirtyTimeout);
    return this._dirtyTimeout = window.setTimeout((function() {
      return _this.trigger('idle');
    }), this.idleTimeout);
  };

  LocalStore.prototype._promiseApi = {};

  LocalStore.prototype._decoratePromise = function(promise) {
    return $.extend(promise, this._promiseApi);
  };

  return LocalStore;

})(Hoodie.Store);
