// Generated by CoffeeScript 1.3.3

Hoodie.Sharing = (function() {

  function Sharing(hoodie) {
    this.hoodie = hoodie;
    Hoodie.Sharing.Instance.hoodie = this.hoodie;
  }

  Sharing.prototype.create = function(options) {
    var sharing;
    if (options == null) {
      options = {};
    }
    sharing = new Hoodie.Sharing.Instance(options);
    return sharing.save();
  };

  Sharing.prototype.load = function(id) {
    var _this = this;
    return this.hoodie.store.load('$sharing', id).pipe(function(obj) {
      return new Hoodie.Sharing.Instance(obj);
    });
  };

  Sharing.prototype.find_or_create = function(options) {
    var defer,
      _this = this;
    defer = this.hoodie.defer();
    this.load(options.id).done(function(sharing) {
      return defer.resolve(sharing);
    }).fail(function() {
      return _this.create(options).then(defer.resolve, defer.reject);
    });
    return defer.promise();
  };

  Sharing.prototype.destroy = function(id) {
    var _this = this;
    return this.load(id).pipe(function(obj) {
      var sharing;
      sharing = new Hoodie.Sharing.Instance(obj);
      return sharing.destroy();
    });
  };

  Sharing.prototype["delete"] = Sharing.prototype.destroy;

  Sharing.prototype.open = function(id, options) {
    if (options == null) {
      options = {};
    }
  };

  return Sharing;

})();
