// Generated by CoffeeScript 1.3.1

define('hoodie/sharing', ['hoodie/sharing/instance'], function(SharingInstance) {
  var Sharing;
  return Sharing = (function() {

    Sharing.name = 'Sharing';

    function Sharing(hoodie) {
      this.hoodie = hoodie;
      SharingInstance.hoodie = this.hoodie;
    }

    Sharing.prototype.create = function(options) {
      if (options == null) {
        options = {};
      }
      return SharingInstance.create(options);
    };

    Sharing.prototype.destroy = function(id) {
      return SharingInstance.destroy(id);
    };

    Sharing.prototype["delete"] = Sharing.prototype.destroy;

    return Sharing;

  })();
});
