// Generated by CoffeeScript 1.3.3

Hoodie.User = (function() {

  function User(hoodie) {
    var _this = this;
    this.hoodie = hoodie;
    return function(userHash) {
      return _this.hoodie.open("user/" + userHash + "/public", {
        prefix: '$public'
      });
    };
  }

  return User;

})();
